### ISSUE TITLE
Implement the /user call

### ISSUE THREAD

**Issue by barranger** [barranger/GeeklistSharp#1]
As per the documentation, we need the ability to get user object via the API Wrapper

**Comment by oakcool** [comment]
I like all that, I will probably be contributing later today, still at work here.

Mateus de Carvalho
More Info

---

 From: Barranger Ridler reply@reply.github.com
To: Mateus oakcool@yahoo.com 
Sent: Thursday, January 26, 2012 2:18 PM
Subject: [GeeklistSharp] Implement the /user call (#1)

As per the documentation, we need the ability to get user object via the API Wrapper

---

Reply to this email directly or view it on GitHub:
https://github.com/barranger/GeeklistSharp/issues/1

**Comment by barranger** [comment]
Not a problem at all.

I'm not entirely sure whether our due date is Monday as in 4 days from
now, or Next Monday as in 11 days from now, so I figured I'd get started
assuming that it is 4 days :)

Barranger

On 12-01-26 5:32 PM, "Mateus"
<reply+i-2987110-c35d5889ec672eeccfe1231d02db4de7e9c38ebc-438877@reply.gith
ub.com> wrote:

**Comment by lsmithmier** [comment]
Agreed, better to deliver early.  I am EST, so I should get started after supper.  I will add a new issue for the code I will cover once I start.

**Comment by amaboura** [comment]
Awesome , if you're going to use a library for oAuth just let us know ,so we'll start doing the same thing with other API calls .

Thank you !

**Comment by barranger** [comment]
Actually I've already checked in the initial component with the initial
oauth flow :)

On 12-01-26 6:01 PM, "Mohamed Amine Aboura"
<reply+i-2987110-c35d5889ec672eeccfe1231d02db4de7e9c38ebc-438877@reply.gith
ub.com> wrote:
